# Generated by Django 5.0.7 on 2024-07-13 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UploadedImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=255)),
                ("face_image", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "left_eye_image",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "right_eye_image",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
